---
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-job-ks-plr
  namespace: "{{ .Values.dataScienceProjectNamespace }}"
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector: {}
  backoffLimit: 10
  template:
    spec:
      containers:
        - args:
            - -ec
            - |-
              echo -n 'Creating PipelineRun to create the first version of the KFP pipeline {{ .Values.modelDeploymentUploadTektonPipelineName }}'
              while ! oc get pipeline {{ .Values.modelDeploymentUploadTektonPipelineName }} 2>/dev/null; do
                echo -n .
                sleep 5
              done; echo

              cat <<EOF | oc create -f -
              apiVersion: tekton.dev/v1beta1
              kind: PipelineRun
              metadata:
                generateName: {{ .Values.modelDeploymentUploadTektonPipelineName }}-ks-plr-
                namespace: {{ .Values.dataScienceProjectNamespace }}
                labels:
                  app.kubernetes.io/instance: {{ .Values.modelDeploymentUploadTektonPipelineName }}
                  pipeline.openshift.io/runtime: quarkus
                  pipeline.openshift.io/type: knative
                annotations:
                  argocd.argoproj.io/hook: PostSync
                  argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
              spec:
                params:
                  - name: APP_NAME
                    value: {{ .Values.modelDeploymentUploadTektonPipelineName }}
                  - name: GIT_PROVIDER
                    value: github
                  - name: GIT_REPO
                    value: '{{ .Values.vcs.uri }}'
                  - name: GIT_REPO_NAME
                    value: '{{ .Values.vcs.name }}'
                  - name: GIT_REVISION
                    value: '{{ .Values.vcs.ref }}'
                  - name: IMAGE_TAG
                    value: '{{ .Values.vcs.ref }}'
                  - name: REVISION_NAME
                    value: v1
                pipelineRef:
                  name: {{ .Values.modelDeploymentUploadTektonPipelineName }}
                serviceAccountName: pipeline
                timeout: 0h15m0s
                workspaces:
                  - name: workspace-source
                    persistentVolumeClaim:
                      claimName: "{{ .Values.instanceName }}-source-pvc"
              EOF
          command:
            - /bin/bash
          image: {{ .Values.setup.image }}
          imagePullPolicy: Always
          name: create-ds-connections
      restartPolicy: Never
      serviceAccount: setup-job
      serviceAccountName: setup-job
