{{- if .Values.sourceWorkspaceSize }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: "{{ .Values.instanceName }}-source-pvc"
  namespace: "{{ .Values.dataScienceProjectNamespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sourceWorkspaceSize }}
{{- end }}
